[package]
name = "panic_lesson"
version = "0.1.0"
authors = ["Gage Pacier <gage@technicallythoughts.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
